version: "3.8"
services:
  # Application
  app:
    build:
      context: ./docker/services/app
      dockerfile: app.dockerfile
    working_dir: /var/www
    volumes:
      - "./src:/var/www"
    networks:
      - petshop_network
  # Web Server
  web:
    build:
      context: ./docker/services/web
      dockerfile: web.dockerfile
    working_dir: /var/www
    volumes:
      - "./src:/var/www"
    ports:
      - "80:80"
    networks:
      - petshop_network
  # Database  
  db:
    image: mariadb:latest
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: adminpass
      MYSQL_USER: "petshop_user"
      MYSQL_PASSWORD: "petshop_pass"
      MYSQL_DATABASE: "petshop_db"
    ports:
      - "3306:3306"
    volumes:
      - "./docker/volumes/mariadb/data:/var/lib/mysql/data/"
      - "./docker/volumes/mariadb/logs:/var/lib/mysql/logs/"
    networks:
      - petshop_network

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - "8081:80"
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - "db"
    networks:
      - petshop_network
networks:
  petshop_network:
